# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example nomada'
on: workflow_dispatch
jobs:
  build_both:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      alphas: '["qwerty"]'
      extra: '["qwerty"]'
      tap: '["qwerty"]'
      nav: '["vi"]'
      clipboard: '["default"]'
      # "fun",
      # "mac",
      # "win"
      layers: '["default"]'
      shield: '["eyelash_corne_left nice_view"]'
      # shield: '["nice_view"]'
      # kconfig: '["CONFIG_ZMK_MOUSE=y\nCONFIG_ZMK_DISPLAY=n"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y"]'
  build_left:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["eyelash_corne_left"]'
      alphas: '["qwerty"]'
      extra: '["qwerty"]'
      tap: '["qwerty"]'
      nav: '["vi"]'
      clipboard: '["default"]'
      # "fun",
      # "mac",
      # "win"
      layers: '["default"]'
      # shield: '["nice_view"]'
      # kconfig: '["CONFIG_ZMK_MOUSE=y\nCONFIG_ZMK_DISPLAY=n"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y"]'
  build_right:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["eyelash_corne_right"]'
      alphas: '["qwerty"]'
      extra: '["qwerty"]'
      tap: '["qwerty"]'
      nav: '["vi"]'
      clipboard: '["default"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y"]'
      # shield: '["eyelash_corne_left nice_view"]'
      # kconfig: '["ONFIG_ZMK_MOUSE=y\nCONFIG_ZMK_DISPLAY=n"]'


# nice_nano_v2
#     shield: kyria_left nice_view_adapter nice_view_gem #updated entry
# - board: nice_nano_v2
#   shield: kyria_left nice_view_adapter nice_view_gem #updated entry
# - board: nice_nano_v2
#   shield: kyria_right nice_view_adapter nice_view_gem #updated entry