# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example nomada'
on: workflow_dispatch
jobs:
  build_left:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["eyelash_corne_left"]'
      shield: '["nice_view_adapter"]'
      # kconfig: '["CONFIG_ZMK_DISPLAY=y"]'
  build_right:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["eyelash_corne"]'
      shield: '[" nice_view_adapter"]'
      # kconfig: '["CONFIG_ZMK_DISPLAY=y"]'


# nice_nano_v2
#     shield: kyria_left nice_view_adapter nice_view_gem #updated entry